"""Add is_system to order_statuses

Revision ID: 302967eeb76e
Revises: 696eba6ac0d3
Create Date: 2026-05-08 10:13:12.965458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302967eeb76e'
down_revision = '696eba6ac0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_statuses', schema=None) as batch_op:
        batch_op.drop_column('is_system')

    # ### end Alembic commands ###
