"""empty message

Revision ID: 696eba6ac0d3
Revises: be0042a8b634
Create Date: 2026-05-08 09:45:01.586483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696eba6ac0d3'
down_revision = 'be0042a8b634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
